# Generated by Django 4.2.16 on 2025-01-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cgame', '0003_alter_customuser_is_active_invite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
