# Generated by Django 4.2.16 on 2025-01-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cgame', '0005_customuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
    ]
